import 'product.dart';

final mockProducts = <Product>[
  const Product(
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&h=200&fit=crop&crop=center',
    title: 'Macbook Pro 2020 (256 GB)',
    location: 'Kinguele - 25 min',
    price: '350000 FCFA',
    likes: 12,
    views: 45,
    comments: 3,
    category: 'Electronics',
    condition: 'Used',
    seller: 'Jean Baptiste',
    postedDate: '2 jours',
    status: 'available',
  ),
  const Product(
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=200&fit=crop&crop=center',
    title: 'Nike Air Max 270 - Taille 42',
    location: 'Libreville Centre - 15 min',
    price: '45000 FCFA',
    likes: 8,
    views: 23,
    comments: 1,
    category: 'Fashion',
    condition: 'New',
    seller: 'Marie Claire',
    postedDate: '1 jour',
    status: 'available',
  ),
  const Product(
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'iPhone 12 Pro Max 128GB',
    location: 'Akebe - 30 min',
    price: '280000 FCFA',
    likes: 25,
    views: 89,
    comments: 7,
    category: 'Electronics',
    condition: 'Used',
    seller: 'Paul Mba',
    postedDate: '3 jours',
    status: 'sold',
  ),
  const Product(
    id: '4',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'Sac à dos Adidas Originals',
    location: 'Nkembo - 20 min',
    price: '25000 FCFA',
    likes: 6,
    views: 18,
    comments: 2,
    category: 'Fashion',
    condition: 'Used',
    seller: 'Sarah Nguema',
    postedDate: '5 jours',
    status: 'available',
  ),
  const Product(
    id: '5',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'Table en bois massif',
    location: 'Montagne Sainte - 45 min',
    price: '120000 FCFA',
    likes: 4,
    views: 12,
    comments: 0,
    category: 'Home',
    condition: 'Used',
    seller: 'Pierre Obiang',
    postedDate: '1 semaine',
    status: 'available',
  ),
  const Product(
    id: '6',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'Vélo électrique Xiaomi',
    location: 'Quartier Louis - 35 min',
    price: '180000 FCFA',
    likes: 15,
    views: 67,
    comments: 4,
    category: 'Transport',
    condition: 'Used',
    seller: 'David Mve',
    postedDate: '4 jours',
    status: 'sold',
  ),
  const Product(
    id: '7',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'Livre scolaire - Mathématiques Terminale',
    location: 'Centre-ville - 10 min',
    price: '8000 FCFA',
    likes: 2,
    views: 8,
    comments: 1,
    category: 'Education',
    condition: 'Used',
    seller: 'Fatou Diallo',
    postedDate: '2 semaines',
    status: 'available',
  ),
  const Product(
    id: '8',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
    title: 'Réfrigérateur Samsung 200L',
    location: 'Nzeng Ayong - 40 min',
    price: '220000 FCFA',
    likes: 9,
    views: 34,
    comments: 2,
    category: 'Home',
    condition: 'Used',
    seller: 'Marc Ondo',
    postedDate: '6 jours',
    status: 'available',
  ),
];

final mockChatItems = <ChatItem>[
  const ChatItem(id: '1', username: 'malbanjunior', timestamp: "Il y'a 30 min", messagePreview: 'Lorem ipsum dolor sit amet, consete...', hasImage: false),
  const ChatItem(id: '2', username: 'mbmk92', timestamp: "Il y'a 1 jour", messagePreview: 'Lorem ipsum dolor sit amet...', hasImage: true, imageUrl: 'https://via.placeholder.com/50x40/cccccc/666666?text=Laptop'),
  const ChatItem(id: '3', username: 'malbanjunior', timestamp: "Il y'a 30 min", messagePreview: 'Lorem ipsum dolor sit amet, consete...', hasImage: false),
  const ChatItem(id: '4', username: 'mbmk92', timestamp: "Il y'a 1 jour", messagePreview: 'Lorem ipsum dolor sit amet...', hasImage: true, imageUrl: 'https://via.placeholder.com/50x40/cccccc/666666?text=Laptop'),
  const ChatItem(id: '5', username: 'malbanjunior', timestamp: "Il y'a 30 min", messagePreview: 'Lorem ipsum dolor sit amet, consete...', hasImage: false),
  const ChatItem(id: '6', username: 'mbmk92', timestamp: "Il y'a 1 jour", messagePreview: 'Lorem ipsum dolor sit amet...', hasImage: true, imageUrl: 'https://via.placeholder.com/50x40/cccccc/666666?text=Laptop'),
];

final mockMessages = <Message>[
  const Message(id: '1', text: 'Salut! Comment ça va?', timestamp: '14:30', isSent: false, senderName: 'malbanjunior'),
  const Message(id: '2', text: 'Salut! Ça va bien merci, et toi?', timestamp: '14:32', isSent: true),
  const Message(id: '3', text: 'Très bien aussi! Tu as vu le nouveau produit sur le site?', timestamp: '14:33', isSent: false, senderName: 'malbanjunior'),
  const Message(id: '4', text: "Oui, il a l'air intéressant. Tu penses l'acheter?", timestamp: '14:35', isSent: true),
  const Message(id: '5', text: 'Je réfléchis encore. Le prix est un peu élevé pour moi.', timestamp: '14:36', isSent: false, senderName: 'malbanjunior'),
  const Message(id: '6', text: "Je comprends. Peut-être qu'il y aura une promotion bientôt?", timestamp: '14:38', isSent: true),
  const Message(id: '7', text: "J'espère! En tout cas, merci pour le conseil.", timestamp: '14:40', isSent: false, senderName: 'malbanjunior'),
  const Message(id: '8', text: "De rien! N'hésite pas si tu as d'autres questions.", timestamp: '14:41', isSent: true),
];

final mockNotifications = <AppNotification>[
  AppNotification(
    id: '1', type: 'message', title: 'Nouveau message',
    message: 'Marie Claire vous a envoyé un message concernant "Nike Air Max 270"',
    timestamp: 'Il y a 5 min', isRead: false,
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=200&fit=crop&crop=center',
  ),
  AppNotification(
    id: '2', type: 'like', title: 'Nouveau like',
    message: 'Paul Mba a aimé votre annonce "iPhone 12 Pro Max"',
    timestamp: 'Il y a 15 min', isRead: false,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
  ),
  AppNotification(
    id: '3', type: 'view', title: 'Vue sur votre annonce',
    message: 'Sarah Nguema a consulté votre annonce "Sac à dos Adidas Originals"',
    timestamp: 'Il y a 1h', isRead: true,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
  ),
  AppNotification(
    id: '4', type: 'sale', title: 'Vente confirmée !',
    message: 'Félicitations ! Vous avez vendu "Macbook Pro 2020" à Jean Baptiste',
    timestamp: 'Il y a 2h', isRead: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&h=200&fit=crop&crop=center',
  ),
  AppNotification(
    id: '5', type: 'offer', title: 'Nouvelle offre',
    message: 'David Mve a fait une offre de 150000 FCFA pour "Vélo électrique Xiaomi"',
    timestamp: 'Il y a 3h', isRead: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
  ),
  AppNotification(
    id: '6', type: 'system', title: 'Mise à jour disponible',
    message: 'Une nouvelle version de BonDeal est disponible. Mettez à jour maintenant !',
    timestamp: 'Il y a 1 jour', isRead: true,
  ),
  AppNotification(
    id: '7', type: 'message', title: 'Nouveau message',
    message: 'Fatou Diallo vous a envoyé un message concernant "Livre scolaire"',
    timestamp: 'Il y a 2 jours', isRead: true,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    productImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop&crop=center',
  ),
];
